### ISSUE TITLE
Extended API: use cases

### ISSUE THREAD

**Issue by domenic** [rakina/find-in-page-api#10]
When thinking about #9, something crystallized for me. I think we can make the extended API use cases a bit clearer. In particular, these two:

> Want to allow browser to search data not currently in the DOM tree by loading the data

The key here is that _the data is in memory, but not in the DOM tree_. The prototypical example here is a virtualized list. The web page can easily search for stuff within the list, and maybe scroll the list to the right position.

This use case needs to know characteristics of the search like the search string, case-sensitivity, whole words only, etc. We should probably flesh out the example code to show how it used the search string etc. to figure out that item 3000 in the infinite list contains the right search string. (Even if we just do so with a comment.)

> The web page wants to supplement results to the browser’s find results

The key here is that _the data is not yet in memory_, but maybe would be if we did some async work. This is the Twitter example.

---

I think we should make these two headlines clearer, to reflect the in memory/not in memory and async vs. not distinction. And incorporate some of the above.

**Comment by rakina** [comment]
I thought that the case 
> Want to allow browser to search data not currently in the DOM tree by loading the data

is for the Twitter example because we are immediately loading the data to DOM before the browser does the find-in-page, and 
>The web page wants to supplement results to the browser’s find results

is for the Infinite List example because we want to notify the browser that there are more results, but not loading it just yet?

**Comment by domenic** [comment]
Hmm, I can see see that point of view. What threw me off was the "maybe when there is an infinite amount of data" feels more like Twitter. (Even though we call it "infinite list", probably more accurate in most cases is "virtualized list".) So in my mind those headlines mapped the other way around. Probably another sign those headlines are too similar :)

Either way, it'd be good to just make it clearer how these two cases are separate, with concrete examples like Twitter (data needs to be fetched from a server) vs. virtualized list (data is in memory, but not in the DOM).

**Comment by rakina** [comment]
> Hmm, I can see see that point of view. What threw me off was the "maybe when there is an infinite amount of data" feels more like Twitter. (Even though we call it "infinite list", probably more accurate in most cases is "virtualized list".) So in my mind those headlines mapped the other way around. Probably another sign those headlines are too similar :)

I see. I've changed the descriptions, do you think it's clearer now?

**Comment by domenic** [comment]
Yes, looks good!
