### ISSUE TITLE
Explain that window.find() is not relevant

### ISSUE THREAD

**Issue by domenic** [rakina/find-in-page-api#11]
Given that it's a topic of recent discussion (https://github.com/whatwg/html/issues/3539), some folks might wonder what the connection is. Add an appendix at the bottom of the main explainer (e.g., "Related technologies") that explains what window.find() does, and how it doesn't help with our use cases at all.

**Comment by rakina** [comment]
I added https://github.com/rakina/find-in-page-api#windowfind, should we also mention FindText API?

**Comment by domenic** [comment]
Yeah, that'd probably be a good idea. The relationship there is a bit more complicated, but probably worth talking about.
