### ISSUE TITLE
Add more non-goals

### ISSUE THREAD

**Issue by domenic** [rakina/find-in-page-api#13]
Inspired by #12 I think it'd be worthwhile to add two non-goals:

- Customizing the appearance of the find-in-page matches.
- Customizing the browser's built-in algorithm for find-in-page matching (e.g. case folding, smart quotes, etc.)

In both cases we should say that these are worthwhile projects for follow-up specs, but not in scope for this work.

/cc @js-choi

**Comment by js-choi** [comment]
@domenic This addresses all my concerns. Hopefully someday these use cases will be addressed, but it is good to explicitly declare them out of scope of this project. Thank you!
