### ISSUE TITLE
List examples of this in the wild

### ISSUE THREAD

**Issue by domenic** [rakina/find-in-page-api#3]
It'd be good to list examples of sites that are currently intercepting Ctrl+F, with a brief description of what they are doing. Also, we could cover the drawbacks of their current approach, and explain whether in the long term they'd benefit most from the openfind API or from the more advanced APIs

Ones I remember are:

- Google Docs / Sheets (maybe we should look at Slides and Office Online too)
- GitHub text editor
- Discourse
- Twitter mobile https://mobile.twitter.com/home (doesn't currently override anything)

Maybe there are more.

Of these I think docs / sheets and twitter would like openfind in the short term and the browser-find API in the long term, probably. Whereas GitHub wants regex search, so it needs openfind. And Discourse wants cross-thread search, so it needs openfind.

In terms of drawbacks of their current approach, the main one is that it doesn't work on mobile, as you noted: it might be worth explaining to the reader what the UX is when people try to search on mobile in these sites.

**Comment by rakina** [comment]
I've added some examples, though I don't really know how to include the Twitter one...

**Comment by domenic** [comment]
Looks really good! I guess we can leave Twitter out for now; I can see how it doesn't quite fit into the flow.
