### ISSUE TITLE
Extended API: findPrev/findNext

### ISSUE THREAD

**Issue by domenic** [rakina/find-in-page-api#9]
The example code shows always loading new data, depending on whether findPrev or findNext is true. This doesn't seem quite right. You really only want to load new data when the user is getting close to the end/beginning of the current set of results.

I think we also need something like lastSeenResultIndex and totalResults? (The name lastSeenResultIndex seems not so good; maybe there is something better.)

Or is there another way of solving this?

Also, as a small issue: probably instead of two booleans, the API should be an enumeration. So, `direction` which is either `"previous"` or `"next"`.

**Comment by rakina** [comment]
By lastSeenResultIndex, do you mean the current active match index? What do you think of this example code?

```js
window.addEventListener("findinginpage", e => {
  if (e.direction == "prev" && e.currentActiveMatchIndex <= LOAD_MATCHES_THRESHOLD) {
    e.waitUntil(loadTweetsBefore(bottomTweet));
  } else if (e.direction == "next" && e.currentActiveMatchIndex >= e.totalMatches - LOAD_MATCHES_THRESHOLD) {
    e.waitUntil(loadNewTweets());
  }
});
```

**Comment by domenic** [comment]
> By lastSeenResultIndex, do you mean the current active match index?

Right.

> What do you think of this example code?

This looks great, with one nit that I think "before" and "new" are reversed? "previous" means going up the page, which in Twitter and other timeline UIs, means newer results. Whereas "next" means going down the page. Right? Or did I confuse myself?

**Comment by rakina** [comment]
> I think "before" and "new" are reversed? "previous" means going up the page, which in Twitter and other timeline UIs, means newer results. Whereas "next" means going down the page. Right? Or did I confuse myself?

Whoops you're right. Changed it!
